website_port: 3000
website_deploy_directory: c:\iisexpress\website
solution_name: BorrowedGames.sln
mvc_project_directory: BorrowedGames 
test_dll: ./BorrowedGames.Tests/bin/debug/BorrowedGames.Tests.dll
test_runner: ./packages/nspec.0.9.58/tools/NSpecRunner.exe
iis_express: C:\Program Files (x86)\IIS Express
