website_port: 3000
website_deploy_directory: c:\iisexpress\website
solution_name: TodoApp #just the name, no .sln extension
mvc_project: TodoApp #just the folder name, no .csproj extension
test_project: TodoApp.Tests #just the folder name, no .csproj extension
test_runner: ./packages/nspec.0.9.62/tools/NSpecRunner.exe
iis_express: C:\Program Files (x86)\IIS Express
